# Generated by Django 3.1.4 on 2020-12-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.FloatField(max_length=1000),
        ),
    ]
